version: '3'
services:
    web:
        build: .
        volumes:
            - "./html:/var/www/html/web"
        ports:
            - "88:80"
        restart: always
        privileged: true
        environment:
            - COLUMNS=236
            - LINES=66
        depends_on:
            - mysql
    mysql:
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: db
        volumes:
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/backup:/backup"

        ports:
            - "3313:3306"

